// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/message.proto

package damian.tab.dsynchro.proto;

public final class ProtoMessages {
  private ProtoMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_synchro_SynchroMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_synchro_SynchroMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_synchro_InitRequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_synchro_InitRequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_synchro_InitResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_synchro_InitResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_synchro_NewConnectionMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_synchro_NewConnectionMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/proto/message.proto\022\007synchro\"" +
      "\270\001\n\016SynchroMessage\022\021\n\tprocessID\030\001 \001(\005\022\r\n" +
      "\005clock\030\002 \003(\005\0221\n\004type\030\003 \001(\0162#.synchro.Syn" +
      "chroMessage.MessageType\022\020\n\010objectID\030\004 \001(" +
      "\t\"?\n\013MessageType\022\010\n\004LOCK\020\000\022\n\n\006UNLOCK\020\001\022\n" +
      "\n\006NOTIFY\020\002\022\016\n\nNOTIFY_ALL\020\003\"4\n\022InitReques" +
      "tMessage\022\017\n\007address\030\001 \001(\t\022\r\n\005ready\030\002 \001(\010" +
      "\"V\n\023InitResponseMessage\022\021\n\tprocessID\030\001 \001" +
      "(\005\022\031\n\021portMapperAddress\030\002 \001(\t\022\021\n\taddress" +
      "es\030\003 \003(\t\"\'\n\024NewConnectionMessage\022\017\n\007addr" +
      "ess\030\001 \001(\tB,\n\031damian.tab.dsynchro.protoB\r" +
      "ProtoMessagesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_synchro_SynchroMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_synchro_SynchroMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_synchro_SynchroMessage_descriptor,
        new java.lang.String[] { "ProcessID", "Clock", "Type", "ObjectID", });
    internal_static_synchro_InitRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_synchro_InitRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_synchro_InitRequestMessage_descriptor,
        new java.lang.String[] { "Address", "Ready", });
    internal_static_synchro_InitResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_synchro_InitResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_synchro_InitResponseMessage_descriptor,
        new java.lang.String[] { "ProcessID", "PortMapperAddress", "Addresses", });
    internal_static_synchro_NewConnectionMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_synchro_NewConnectionMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_synchro_NewConnectionMessage_descriptor,
        new java.lang.String[] { "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
