// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/message.proto

package damian.tab.dsynchro.proto;

public interface SynchroMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:synchro.SynchroMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 processID = 1;</code>
   * @return The processID.
   */
  int getProcessID();

  /**
   * <code>repeated int32 clock = 2;</code>
   * @return A list containing the clock.
   */
  java.util.List<java.lang.Integer> getClockList();
  /**
   * <code>repeated int32 clock = 2;</code>
   * @return The count of clock.
   */
  int getClockCount();
  /**
   * <code>repeated int32 clock = 2;</code>
   * @param index The index of the element to return.
   * @return The clock at the given index.
   */
  int getClock(int index);

  /**
   * <code>.synchro.SynchroMessage.MessageType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.synchro.SynchroMessage.MessageType type = 3;</code>
   * @return The type.
   */
  damian.tab.dsynchro.proto.SynchroMessage.MessageType getType();

  /**
   * <code>string objectID = 4;</code>
   * @return The objectID.
   */
  java.lang.String getObjectID();
  /**
   * <code>string objectID = 4;</code>
   * @return The bytes for objectID.
   */
  com.google.protobuf.ByteString
      getObjectIDBytes();
}
