// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/src/main/proto/message.proto

package damian.tab.core.proto;

public interface InitResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:synchro.InitResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 processID = 1;</code>
   * @return The processID.
   */
  int getProcessID();

  /**
   * <code>string portMapperAddress = 2;</code>
   * @return The portMapperAddress.
   */
  java.lang.String getPortMapperAddress();
  /**
   * <code>string portMapperAddress = 2;</code>
   * @return The bytes for portMapperAddress.
   */
  com.google.protobuf.ByteString
      getPortMapperAddressBytes();

  /**
   * <code>repeated string addresses = 3;</code>
   * @return A list containing the addresses.
   */
  java.util.List<java.lang.String>
      getAddressesList();
  /**
   * <code>repeated string addresses = 3;</code>
   * @return The count of addresses.
   */
  int getAddressesCount();
  /**
   * <code>repeated string addresses = 3;</code>
   * @param index The index of the element to return.
   * @return The addresses at the given index.
   */
  java.lang.String getAddresses(int index);
  /**
   * <code>repeated string addresses = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the addresses at the given index.
   */
  com.google.protobuf.ByteString
      getAddressesBytes(int index);
}
