// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/src/main/proto/message.proto

package damian.tab.core.proto;

public interface InitRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:synchro.InitRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>bool ready = 2;</code>
   * @return The ready.
   */
  boolean getReady();
}
